// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders: number;
  paidOrders: number;
  notPaidOrders: number;
  numberOfclients: number;
  numberOfProducts: number;
  productsWhitNoInventory: number;
  lowInventory: number;
}
